package com.etendoerp.db.extended.vector;

/** Stable error codes exposed by the generic vector API. */
public enum VectorErrorCode {
  PGVECTOR_NOT_ENABLED, VECTOR_COLLECTION_NOT_FOUND, VECTOR_DIMENSION_MISMATCH,
  VECTOR_INVALID_METADATA, VECTOR_EXTENSION_CONFLICT, VECTOR_INDEX_OPERATION_FAILED,
  VECTOR_OUTBOX_OPERATION_FAILED
}
